@startuml

!includeurl https://gist.githubusercontent.com/Arnaud-Bonneuil/c317a7a30bed7d64e2b5b1f558ac00cf/raw/sober.puml

!include T_Board_State!T_Board_State
!include T_Position!T_Position
!include T_Position!T_Rank
!include T_Position!T_File

interface Board_Management {
  {abstract} + Move_Piece( IN initial:T_Position, IN final:T_Position, OUT state:T_Board_State )  
  {abstract} + Get_State( OUT state:T_Board_State )
}

class Board

Board_Management <|.. Board

@enduml